### ISSUE TITLE
Wrong Link

### ISSUE THREAD

**Issue by slaout** [Decathlon/ara#1]
Hello Sylvain,

I'm glad you were able to complete the open-sourcing of ARA: congratulations for the remaining work :-)
And congratulations on a personal note too ;-)

When viewing this page:

https://github.com/Decathlon/ara/blob/master/doc/user/main/UserDocumentation.adoc

Clicking "User Walkthrough" leads to a 404.

There is a "/user" part to be removed in the URL.

**Comment by dktsni** [comment]
Hi Seb ! 

Won't be able to do it without your hard work, so thanks to you :D 
Thanks for the personal note 😄 

Okidoki for this issue, must be a remaining of the past documentation management.

I'll fix it in the next version ;) So stay tuned ! :D 

Thanks again, and be my guest if you want to submit PR on your little baby bird :D

**Comment by slaout** [comment]
Fixed it with https://github.com/Decathlon/ara/pull/2

Lol, you flagged this issue as "good first issue" ;-)
Shoud l revert my PR to let newcomers fix it? :-)

**Comment by dktsni** [comment]
Nah, you can fix it, no worries ;) 

I just put directly the flags after reviewing each issues, it can be useful to the visibility of Ara ;) 

Thanks for the fix btw :)
