### ISSUE TITLE
Unable to modify the feature's label

### ISSUE THREAD

**Issue by ghost** [Decathlon/ara#11]
The link between the feature and the scenario is broken when the feature's label is changed.

To reproduce :
- Go to ARA > Fonctionnalities > Cartography
- Edit a fonctionnality > Change the name > Save

The scenarios in the columne "Coverage by scenarios" are gone.

![bug-ara](https://user-images.githubusercontent.com/49676120/56195763-db486a00-6035-11e9-9c01-adf0143a4a7f.png)

**Comment by slaout** [comment]
Hello, I don't have a running ARA to try to reproduce: on the server-side, it seems well handled: perhaps a client-side bug.
=> Do they reappear on page refresh (pressing F5)?

**Comment by DemuyterThifaine** [comment]
Hello,

I think it's a cache problem: I changed the label yesterday and the associated scenarios are well displayed this morning.

**Comment by dktsni** [comment]
I'll check if this is a cache issue or the client side which keeps old datas and don't refresh.

I'll keep you in touch.

**Comment by omar-chahbouni-decathlon** [comment]
I was unable to reproduce this behavior.
