### ISSUE TITLE
Querydsl error during Ara installation

### ISSUE THREAD

**Issue by sarchkak** [Decathlon/ara#119]
I'm trying to instal Ara on a MacOs Mojave version 10.14.5
I've followed the instruction on 'How to build it and make it work in 2 minutes'.
I make sure to start the ara-db before 'mvn clean install -Pdev -DskipPitest -Dmaven.test.skip=true' 
But during this install, i get an error on querydsl (refer to screenshot).
Docker Version is 2.0.0.3
![Ara-server-Problem](https://user-images.githubusercontent.com/51445749/59157875-c5de4200-8ab2-11e9-840e-7a76f40a0943.png)

**Comment by dktsni** [comment]
Hi @sarchkak !

Unfortunately, this bug is already identified and a fix is in progress (see #97 ). We will provide the new version this month.

On your local case, could you check that your docker container is up and running on port 5432, which needs to be exposed on host ?

**Comment by dktsni** [comment]
Hi @sarchkak 

We rework the way ARA is installed locally to remove any dependencies with Querydsl in the version 4.0.0 (which is now on master).

I strongly encourage you to use it and give us any feedback :D 

Thanks for your interest in ARA !

dktsni
