### ISSUE TITLE
Add possibility to export all or a part of the cartography of functionalities, and to import it to another ARA project

### ISSUE THREAD

**Issue by Dnowakdn** [Decathlon/ara#135]

**Comment by Dnowakdn** [comment]
**Add possibility to export all or a part of the cartography of functionalities, and to import it to another ARA project**

**Context:**
A part of the functionality tree is present on the "ARA_Project1".
"ARA_Project2" is created, and with 0 tree (0 functionality).
The goal of this issue is to allow export of a part of the tree from "ARA_Project1", and import of the exported tree in the "ARA_Project2" tree.

**Expected:**
The exported tree is always present on the "ARA_Project1".
I can import the exported tree to the folder I want on the "ARA_Project2".
IDs of functionalities are renumbered, following the IDs of the "ARA_Project2". 0 link with existing TNR on "ARA_Project2".

**Comment by dktsni** [comment]
Here is the list of tasks which will be implemented : 

* Frontend :
   * [ ] In the Functionality -> Cartography, replace the following button 
![Screenshot 2019-10-07 at 10 15 00](https://user-images.githubusercontent.com/45944760/66295508-caddc180-e8eb-11e9-96ed-831149c78af8.png) by this one 
![Screenshot 2019-10-07 at 10 17 52](https://user-images.githubusercontent.com/45944760/66295510-cfa27580-e8eb-11e9-8c59-738aeb85ad71.png)

    * [ ] Add a menu of three element on click on this button : `Clear filters`, `Import Functionalities`, `Export Functionalities`
    * [ ] Remap the previously removed button (step 1) to `Clear filters`
    * [ ] Display a modal popup when the user clicks on `Export Functionalities` to let the user choose the kind of export he/she wants. (For now, the export will propose two kind : ARA-format, and SquashTM-format), then trigger the export on a click to `Ok`.

* Backend :
    * [ ] Add an endpoint to list the available export methods (maybe in the `FunctionalityResource` with an OPTION call to `{host}/api/projects/{projectId}/functionalities/export` ?)
    * [ ] Add an export endpoint in the `FunctionalityResource`, something like a GET to `{host}/api/projects/{projectId}/functionalities/export`
    * [ ] Add an import endpoint in the `FunctionalityResource`, something like a POST to `{host}/api/projects/{projectId}/functionalities/import`
    * [ ] Create a modular architecture with the new exporters/importers to allow external contributors to add their custom ones.
   * [ ] Create the exporter/importer for a ARA specific format (like a transfer of functionalities from one project to another)
   * [ ] Create the exporter for a SquashTM specific format (export a cartography to import it as requirements)

Here are some points to keep in mind while developing this feature : 
* Surround it with a Feature flipping to avoid breaking changes (cf https://github.com/Decathlon/ara/blob/master/client/README.adoc#managing-feature-flipping and 
https://github.com/Decathlon/ara/blob/master/server/README.adoc )
* Test the case where the user wants to import functionalities in a project which already have functionalities (merge mode) : what to do in case of conflict ?
