### ISSUE TITLE
Windows instal MySql in Docker

### ISSUE THREAD

**Issue by juliensz** [Decathlon/ara#15]
The script manage-db.sh didn't work on Windows beacause the path in docker run is wrong : 
Like this now : 
`docker run --name ara-db -e MYSQL_ROOT_PASSWORD=$PASSWORD -v /../../dbara/:/var/lib/mysql -v //c/Users/$USER/Documents/ara-master/db/db-conf:/etc/mysql/conf.d -v //c/Users/$USER/Documents/ara-master/db/db-sql:/docker-entrypoint-initdb.d -p 3306:3306 -d mysql:5.5`
But on windows need a absolut path for this working : 
`docker run --name ara-db -e MYSQL_ROOT_PASSWORD=$PASSWORD -v C:/Users/$USER/Documents/dbara/:/var/lib/mysql -v C:/Users/$USER/Documents/ara-master/db/db-conf:/etc/mysql/conf.d -v C:/Users/$USER/Documents/ara-master/db/db-sql:/docker-entrypoint-initdb.d -p 3306:3306 -d mysql:5.5`

**Comment by dktsni** [comment]
Will be released in version 4.0.0
