### ISSUE TITLE
Saving last success video

### ISSUE THREAD

**Issue by GeoffreyBoulay** [Decathlon/ara#160]
Hello,

When a front NRT works, we don't save the video.

Today, we would like to compare the last success result to the fail result.

The reason is when a feature is broken after several months, we can forget the good behaviour.

**Comment by dktsni** [comment]
Hi @GeoffreyBoulay 

Thx for your issue 😃 

(Just for the record, for the next issues, could you please use the Feature Request template please ?) 

But again thanks for your issue, it's an interesting feature to add to ARA.

dktsni

**Comment by dktsni** [comment]
Replaced by #161
