### ISSUE TITLE
Saving last success video

### ISSUE THREAD

**Issue by GeoffreyBoulay** [Decathlon/ara#161]
**What it's the actual situation on ARA ?**
Video is saved when NRT fail.

**Describe the solution you'd like**
To unterstand while some NRT failled,  I would like to see the video of a NRT last success.

Today, we would like to compare the last success result to the fail result.

The reason is when a feature is broken after several months, we can forget the good behaviour.

**Describe alternatives you've considered**

**Additional context**

**Comment by dktsni** [comment]
Hi @GeoffreyBoulay 

Thx for remaking the issue :D I'll close the other one ;)

dktsni

**Comment by dktsni** [comment]
Duplicated with #225
