### ISSUE TITLE
[HIGH] Functionalities_Cartography_Filter

### ISSUE THREAD

**Issue by z25clave** [Decathlon/ara#191]
**Filter Functionalities by identifier**

- [ ] Add functionality in ARA
- [ ] Add NRT

**Filter Functionalities by name**
- [ ] Add functionality in ARA
- [ ] Add NRT

**Filter Functionalities by team**
- [ ] Add functionality in ARA
- [ ] Add NRT

**Filter Functionalities by severity**
- [ ] Add functionality in ARA
- [ ] Add NRT

**Filter Functionalities by countries**
- [ ] Add functionality in ARA
- [ ] Add NRT

**Expand all**
- [ ] Add functionality in ARA
- [ ] Add NRT

**Collapse all**
- [ ] Add functionality in ARA
- [ ] Add NRT

**Comment by dktsni** [comment]
Moved to another project
