### ISSUE TITLE
[HIGH] Functionalities_Cartography_Table_AddFolder

### ISSUE THREAD

**Issue by z25clave** [Decathlon/ara#193]
**Create folder above this folder (Create)**
- [ ] Add functionality in ARA
- [ ] Add NRT

**Create folder inside this folder (Create)**
- [ ] Add functionality in ARA
- [ ] Add NRT

**Create folder below this folder (Create)**
- [ ] Add functionality in ARA
- [ ] Add NRT

**Create folder above this functionality (Create)**
- [ ] Add functionality in ARA
- [ ] Add NRT

**Create folder below this functionality (Create)**
- [ ] Add functionality in ARA
- [ ] Add NRT

**Comment by dktsni** [comment]
Moved to another project
