### ISSUE TITLE
[HIGH] Functionalities_Cartography_Table_AddFunctionality

### ISSUE THREAD

**Issue by z25clave** [Decathlon/ara#195]
**Create functionality above this folder (Create)**
- [ ] Add functionality in ARA
- [ ] Add NRT

**Create functionality below this folder (Create)**
- [ ] Add functionality in ARA
- [ ] Add NRT

**Create functionality above this functionalty (Create)**
- [ ] Add functionality in ARA
- [ ] Add NRT

**Create functionality below this functionalty (Create)**
- [ ] Add functionality in ARA
- [ ] Add NRT

**Comment by dktsni** [comment]
Moved to another project
