### ISSUE TITLE
[HIGH] Problems

### ISSUE THREAD

**Issue by z25clave** [Decathlon/ara#215]
**Filter Problems by Status**
- [ ] Add functionality in ARA
- [ ] Add NRT

**Filter Problems by Team**
- [ ] Add functionality in ARA
- [ ] Add NRT

**Use page navigation : page number**
- [ ] Add functionality in ARA
- [ ] Add NRT

**Use page navigation : number of result / page**
- [ ] Add functionality in ARA
- [ ] Add NRT

**Comment by dktsni** [comment]
Moved to another project
