### ISSUE TITLE
[HIGH] Problems_OneProblem_Problem

### ISSUE THREAD

**Issue by z25clave** [Decathlon/ara#216]
**Acces to the workitem (go to ....)**
- [ ] Add functionality in ARA
- [ ] Add NRT

**Delete the problem (Delete the problem)**
- [ ] Add functionality in ARA
- [ ] Add NRT

**Edit the problem properties (Save)**
- [ ] Add functionality in ARA
- [ ] Add NRT

**Close the problem (Assign Root Cause & Close problem)**
- [ ] Add functionality in ARA
- [ ] Add NRT

**Refresh status from workitem now**
- [ ] Add functionality in ARA
- [ ] Add NRT

**Open actions menu**
- [ ] Add functionality in ARA
- [ ] Add NRT

**Comment by dktsni** [comment]
Moved to another project
