### ISSUE TITLE
[HIGH] Problems_OneProblem_Patterns_EditPattern

### ISSUE THREAD

**Issue by z25clave** [Decathlon/ara#218]
**Edit pattern (use each option)**
- [ ] Add functionality in ARA
- [ ] Add NRT

**Open the screenshot of the matching error**
- [ ] Add functionality in ARA
- [ ] Add NRT

**Open the video of the matching error**
- [ ] Add functionality in ARA
- [ ] Add NRT

**Play, Manage sound, screen size and other options on the video of the matching error**
- [ ] Add functionality in ARA
- [ ] Add NRT

**Open the history for the scenario of the matching error**
- [ ] Add functionality in ARA
- [ ] Add NRT

**Use execution navigation (bullet)**
- [ ] Add functionality in ARA
- [ ] Add NRT

**Use execution navigation (button)**
- [ ] Add functionality in ARA
- [ ] Add NRT

**Filter the history for the scenario**
- [ ] Add functionality in ARA
- [ ] Add NRT

**Open Debug information menu**
- [ ] Add functionality in ARA
- [ ] Add NRT

**Go to the Error's page => Go to the execution**
- [ ] Add functionality in ARA
- [ ] Add NRT

**Use page navigation : number of result / page**
- [ ] Add functionality in ARA
- [ ] Add NRT

**Save pattern modification**
- [ ] Add functionality in ARA
- [ ] Add NRT

**Comment by dktsni** [comment]
Moved to another project
