### ISSUE TITLE
[HIGH] Problems_OneProblem_Patterns_MovePattern

### ISSUE THREAD

**Issue by z25clave** [Decathlon/ara#219]
**Move Pattern To another existing problem - only one pattern (Move Pattern & Delete Problem)**
- [ ] Add functionality in ARA
- [ ] Add NRT

**Filter Problems by Status (popup)**
- [ ] Add functionality in ARA
- [ ] Add NRT

**Filter Problems by Team (popup)**
- [ ] Add functionality in ARA
- [ ] Add NRT

**Use page navigation : page number (popup)**
- [ ] Add functionality in ARA
- [ ] Add NRT

**Use page navigation : number of result / page (popup)**
- [ ] Add functionality in ARA
- [ ] Add NRT

**Move To (Save)**
- [ ] Add functionality in ARA
- [ ] Add NRT

**Comment by dktsni** [comment]
Moved to another project
