### ISSUE TITLE
[HIGH] Problems_OneProblem_Patterns_DeletePattern

### ISSUE THREAD

**Issue by z25clave** [Decathlon/ara#220]
**Delete Pattern - only one pattern (Delete Pattern & Problem)**
- [ ] Add functionality in ARA
- [ ] Add NRT

**Delete Pattern - more than one pattern (Delete Pattern)**
- [ ] Add functionality in ARA
- [ ] Add NRT

**Comment by dktsni** [comment]
Moved to another project
