### ISSUE TITLE
[HIGH] Problems_OneProblem_MatchingErrors

### ISSUE THREAD

**Issue by z25clave** [Decathlon/ara#221]
**Use page navigation : page number**
- [ ] Add functionality in ARA
- [ ] Add NRT

**Use page navigation : number of result / page**
- [ ] Add functionality in ARA
- [ ] Add NRT

**Display the failed step in the scenario execution**
- [ ] Add functionality in ARA
- [ ] Add NRT

**Display the exception for scenario**
- [ ] Add functionality in ARA
- [ ] Add NRT

**Open the history for the scenario of the matching error**
- [ ] Add functionality in ARA
- [ ] Add NRT

**Open actions menu**
- [ ] Add functionality in ARA
- [ ] Add NRT

**Comment by dktsni** [comment]
Moved to another project
