### ISSUE TITLE
Create Folder in ARA cartography 

### ISSUE THREAD

**Issue by BenjaminDupont** [Decathlon/ara#227]
**Describe the bug**
In cartography part, When i would like to create a folder inside a folder, my new folder do not appear

**To Reproduce**
1. Go to http://localhost:8080/#/projects/the-demo-project/functionalities/coverage
2. Click on "Cartography" Tab
3. When i would create a folder inside this folder for example " Manage something"
4.  My new folder is not refresh 

**Expected behavior**
Refresh My new folder 

**Environment**
 - Browser [chrome]

**Comment by dktsni** [comment]
Hi @BenjaminDupont 

I can't reproduce this issue locally. 

Could you provide us a screenshot of your problem ? 

Do you use the following menu ?
<img width="388" alt="Screenshot 2020-01-08 at 14 28 14" src="https://user-images.githubusercontent.com/45944760/71981676-25582800-3223-11ea-8cce-7262ac4ec720.png">

**Comment by dktsni** [comment]
Ok, I was able to reproduce the issue if I apply a filter on Team before creating the Folder.

Working on that.
