### ISSUE TITLE
Add support for Cerberus

### ISSUE THREAD

**Issue by Nouxx** [Decathlon/ara#271]
**What it's the actual situation on ARA ?**
It's not possible to link [Cerberus](https://github.com/cerberustesting) execution campaigns to ARA.

**Describe the solution you'd like**
The solution isn't clear yet since the two solutions are overlapping on reporting: Cerberus have its own Report KPI and CI/CD Integration. There is no "go to" solution, there is a essential conception work to be done.

**Additional context**
Waiting for a meeting with @omar-chahbouni-decathlon

**Comment by Nouxx** [comment]
Following today's meeting:

TO DO : 
- [ ] output format from Cerberus to describe
- [ ] decision on how to consume the data (from ara standpoint)

**Comment by Nouxx** [comment]
The validated ouput format from Cerberus is describe in this [issue](https://github.com/cerberustesting/cerberus-source/issues/2204).

You should now be able to start developing the "cerberus adapter" based on this :) 

The CI pipe will be able to fetch execution data from Cerberus using a new endpoint that it going to be developed on our side.

**Comment by VviGit** [comment]
We will develop this adapter based on new ARA APIS
Prerequisite #368
