### ISSUE TITLE
Can't create a problem

### ISSUE THREAD

**Issue by Nouxx** [Decathlon/ara#412]
**Describe the bug**
I can't create a problem from an execution page

**To Reproduce**
1. Go to  https://ara.build-factory.decathlon.io/projects/instore-dataset/executions/35425?type=generate-orders&country=fr&severity=sanity-check
2. Interact with any fields in the problem creation form
3. Contemplate the 504 error popup

**Expected behavior**
No error, or if so, a clearer description.

**Screenshots**
![image](https://user-images.githubusercontent.com/30227758/110335831-901e1280-8024-11eb-99ed-40113c6a5523.png)

**Environment**
 - OS: Mac OS Catalina
 - Browser: Chrome

**Comment by TroyonGuillaume** [comment]
Hi @Nouxx 
Thank you for your interest in our tools.
We have corrected the problem. Sorry for the inconvenience

Have a good day
