### ISSUE TITLE
Unable to delete comments on functionalities part

### ISSUE THREAD

**Issue by TroyonGuillaume** [Decathlon/ara#5]
**Problem description:** Unable to delete comments on functionalities part

**Actual Result:** 
1) Go on functionalities tab
2) Click on the pencil to edit a feature (Take a feature that already a comment)
3) Delete the comment and click on save button
**Comment is not deleted** ==> [**Video Here**](https://www.screencast.com/t/xVPqOU5I02)

**Expected Result:**
Comment must be deleted

**Comment by dktsni** [comment]
Hi @TroyonGuillaume !

Thx for your issue ! I can still reproduce this behavior in version 4.0.0 of ARA.
I'll start the fix of it and it will be included in version 4.1.0 :) 

dktsni

**Comment by dktsni** [comment]
It seems, that in the backend and database, the comment is correctly deleted, but what leads you to the fact it isn't, is that the frontend isn't refreshed automatically. 

If you refresh it manually, you'll see that the comment is deleted.

PR on the way.

**Comment by dktsni** [comment]
Fix implemented in version 4.1.0
