### ISSUE TITLE
Add "Github" bugtracker adapter

### ISSUE THREAD

**Issue by JulienBarlet** [Decathlon/ara#6]
As the native "Rational Team Concert" adapter which allow to make relations between "problems" in ARA and "Defect" in the bugtracker, it will be wonderful to make the same relation with "Github".

**Comment by dktsni** [comment]
Hi Julien !

This feature is already done in the version 3.1.0 :) https://github.com/Decathlon/ara/releases/tag/v3.1.0

You can use it in your Project's setting page, the Defect Adapter dropdown menu will contains RTC and GitHub :)
